### PR TITLE
Remove usage of array_get

### PR DESCRIPTION
**Pull request by speeddragon**
Remove usage of array_get to use in non Laravel projects.

### CODE REVIEW

**Comment by speeddragon** [comment]
@jonnywilliamson Do you know why the build failed in PHP 5.6 ? Doesn't appear to be a issue with my code, but I'm not sure.

**Comment by jonnywilliamson** [comment]
@speeddragon thanks for this!

I'm currently away on a work trip for 2 weeks. Home very soon and I'll merge/fix this then.

**Comment by B3none** [comment]
Please could you take a look at this, I am relying on this merge

**Comment by speeddragon** [comment]
A rebuild should work to make this green. @jonnywilliamson can you check that ?

**Comment by jonnywilliamson** [comment]
Sorry guys this dropped under my radar.

Let me see what i can do.

**Comment by B3none** [comment]
Hey, thanks for the update. Can you please release this :)

**Comment by jonnywilliamson** [comment]
v0.0.3 tagged.

**Pull request merged**
